# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: galaxian

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: logger

# ---------------------------------------
# User Section
# ---------------------------------------

model:
  backbone: False

env:
  max_episode_steps: 100

train:
  lr: 1e-3

sampling:
  percentile: 80
  batch_size: 100
  epochs: 50

export:
  tensorboard: runs
  video_folder: video
  model: galaxian.pth